heat_template_version: 2015-04-30

parameters:
  ipam1:
    type: string
    description: Name of IPAM to be created
  vn1:
    type: string
    description: Name of VN to be created
  subnet_ip_prefix:
    type: string
    description: subnet prefix for the VN
  subnet_ip_prefix_len:
    type: string
    description: subnet prefix len for the VN
  subnets_addr_from_start_true:
    type: boolean
    description: Address allocation from start of the pool
  rt_table_name:
    type: string
    description: Name of the Route Table
  route_prefix:
    type: string
    description: Route Prefix
  route_next_hop:
    type: string
    description: Route Next Hop
  next_hop_type:
    type: string
    description: Next Hop Type

resources:
  ipam:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: { get_param: ipam1 }

  vn:
    type: OS::ContrailV2::VirtualNetwork
    depends_on: [ ipam, rt_table ]
    properties:
      name: { get_param: vn1 }
      network_ipam_refs: [{ get_resource: ipam }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: subnet_ip_prefix },
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: subnet_ip_prefix_len },
                },
              network_ipam_refs_data_ipam_subnets_addr_from_start: { get_param: subnets_addr_from_start_true },
            }]
         }]
      route_table_refs: [{ get_resource: rt_table }]

  rt_table:
      type: OS::ContrailV2::RouteTable
      properties:
        name: { get_param: rt_table_name }
        routes:
          {
	    routes_route:
		[{
		  routes_route_prefix: { get_param: route_prefix },
	          routes_route_next_hop: { get_param: route_next_hop },
		  routes_route_next_hop_type: { get_param: next_hop_type }
	        }],
	   }
